# Deploy Android to Firebase App Distribution
#
# Copy to: .github/workflows/deploy-firebase-android.yml
#
# Required secrets:
#   FIREBASE_APP_ID_ANDROID - Firebase Android App ID
#   FIREBASE_SERVICE_ACCOUNT - Firebase service account JSON

name: Deploy Android to Firebase

on:
  push:
    tags:
      - 'v*-beta*'
      - 'v*-alpha*'
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release notes'
        required: false
        default: 'New build available'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: |
            ${{ github.event.inputs.release_notes || format('Build from {0}', github.sha) }}

            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
