// Template: main.dart
//
// This replaces the generated main.dart after flutter create.
// Customize based on project configuration.

import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
// CONDITIONAL: Only if Supabase = yes
// import 'package:supabase_flutter/supabase_flutter.dart';

// Import app.dart (generated by /core skill)
// import 'app.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load environment variables
  await dotenv.load(fileName: '.env');

  // CONDITIONAL: Only if Supabase = yes
  // Initialize Supabase
  // await Supabase.initialize(
  //   url: dotenv.env['SUPABASE_URL']!,
  //   anonKey: dotenv.env['SUPABASE_ANON_KEY']!,
  // );

  runApp(
    const ProviderScope(
      // TODO: Replace with App() after running /core
      child: _PlaceholderApp(),
    ),
  );
}

// Placeholder until /core generates app.dart
class _PlaceholderApp extends StatelessWidget {
  const _PlaceholderApp();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '{APP_NAME}', // TODO: Replace with actual app name
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Color(0xFF{PRIMARY_COLOR})),
        useMaterial3: true,
      ),
      home: const Scaffold(
        body: Center(
          child: Text('Run /core to generate app infrastructure'),
        ),
      ),
    );
  }
}

// ===========================================================================
// FULL VERSION (After /core is run)
// ===========================================================================
//
// import 'package:flutter/material.dart';
// import 'package:flutter_dotenv/flutter_dotenv.dart';
// import 'package:flutter_riverpod/flutter_riverpod.dart';
// import 'package:supabase_flutter/supabase_flutter.dart';
//
// import 'app.dart';
//
// Future<void> main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//
//   await dotenv.load(fileName: '.env');
//
//   await Supabase.initialize(
//     url: dotenv.env['SUPABASE_URL']!,
//     anonKey: dotenv.env['SUPABASE_ANON_KEY']!,
//   );
//
//   runApp(const ProviderScope(child: App()));
// }
